import 'package:flutter_diablo2_exchange/index.dart';

class SignUpScreen extends StatelessWidget {
  const SignUpScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
      children: <Widget>[
        Container(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage("assets/images/sign_up_background.jpg"),
              fit: BoxFit.cover,
            ),
          ),
        ),
        Align(
          alignment: Alignment.center,
          child: SingleChildScrollView(
            child: Column(
              children: [
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
                Text("Hello background"),
              ],
            ),
          ),
        )
      ],
    ));
  }
}
